let list = [
    { image: 'http://www.longjinph.com/test/wx/newsInfo/0420-02/list.jpg', title: '老龄化社会之下，广告营销的新血液', context: '如今，当我们谈论起广告营销里的新受众，第一个想到的大部分都是年轻人，GenZ，00后等等，但是我们很有可能忽视了另一个逐渐壮大的消费群体——老年人...', date: '04.20', year: '2020', newsInfo:["http://www.longjinph.com/test/wx/newsInfo/0420-02/01.png","http://www.longjinph.com/test/wx/newsInfo/0420-02/02.png","http://www.longjinph.com/test/wx/newsInfo/0420-02/03.png","http://www.longjinph.com/test/wx/newsInfo/0420-02/04.png","http://www.longjinph.com/test/wx/newsInfo/0420-02/05.png" ]},
    { image: 'http://www.longjinph.com/test/wx/newsInfo/0420-01/list.jpg', title: '如何让你的品牌价值凸显？', context: '这一次疫情的确带来巨大的影响，同时我们也看到疫情之下的经济问题变得极具挑战。面对危机和挑战，做出科学...', date: '04.20', year: '2020', newsInfo: ["http://www.longjinph.com/test/wx/newsInfo/0420-02/01.png","http://www.longjinph.com/test/wx/newsInfo/0420-02/02.png","http://www.longjinph.com/test/wx/newsInfo/0420-02/03.png","http://www.longjinph.com/test/wx/newsInfo/0420-02/04.png","http://www.longjinph.com/test/wx/newsInfo/0420-02/05.png" ]},
    { image: 'http://www.longjinph.com/test/wx/newsInfo/0413-02/list.jpg', title: '营销新关口，广告如何投放？', context: '2019年对于营销行业来讲，可以说是具有拐点性的一年了。经济下行的情况下，广告行业的日子不好过，广告主...', date: '04.13', year: '2020', newsInfo: ["http://www.longjinph.com/test/wx/newsInfo/0420-02/01.png","http://www.longjinph.com/test/wx/newsInfo/0420-02/02.png","http://www.longjinph.com/test/wx/newsInfo/0420-02/03.png","http://www.longjinph.com/test/wx/newsInfo/0420-02/04.png","http://www.longjinph.com/test/wx/newsInfo/0420-02/05.png" ] },
    { image: '/image/news/newspro.png', title: '地缘风险开始降温 金价短期内上...', context: '上周末举行的G7峰会不欢而散，因特朗普在推特表示要求美国代表不在联合公报上签名。不过美朝关系缓和也意味着地缘风险开始', date: '08.06', year: '2020' },
    { image: '/image/news/newspro.png', title: '地缘风险开始降温 金价短期内上...', context: '上周末举行的G7峰会不欢而散，因特朗普在推特表示要求美国代表不在联合公报上签名。不过美朝关系缓和也意味着地缘风险开始', date: '08.06', year: '2020' },
    { image: '/image/news/newspro.png', title: '地缘风险开始降温 金价短期内上...', context: '上周末举行的G7峰会不欢而散，因特朗普在推特表示要求美国代表不在联合公报上签名。不过美朝关系缓和也意味着地缘风险开始', date: '08.06', year: '2020' },
    { image: '/image/news/newspro.png', title: '地缘风险开始降温 金价短期内上...', context: '上周末举行的G7峰会不欢而散，因特朗普在推特表示要求美国代表不在联合公报上签名。不过美朝关系缓和也意味着地缘风险开始', date: '08.06', year: '2020' },
    { image: '/image/news/newspro.png', title: '地缘风险开始降温 金价短期内上...', context: '上周末举行的G7峰会不欢而散，因特朗普在推特表示要求美国代表不在联合公报上签名。不过美朝关系缓和也意味着地缘风险开始', date: '08.06', year: '2020' },
]

export default list;